version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
    open-pull-requests-limit: 15
    groups:
      all-maven:
        patterns: [ "*" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
    groups:
      all-actions:
        patterns: [ "*" ]
